// <auto-generated />
using Estrutura.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Estrutura.Web.API.Migrations
{
    [DbContext(typeof(EstruturaContext))]
    [Migration("20210226170716_initMysql")]
    partial class initMysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Estrutura.Web.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Role")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Anderson",
                            LastName = "Oliveira",
                            Password = "123",
                            Role = "Admin",
                            Token = "",
                            Username = "aos"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "keli",
                            LastName = "Silva",
                            Password = "123",
                            Role = "User",
                            Token = "",
                            Username = "keli"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Samuel",
                            LastName = "Claro",
                            Password = "123",
                            Role = "User",
                            Token = "",
                            Username = "samuel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
